repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # - repo: https://github.com/pypa/pip-audit
  #   rev: v2.4.4
  #   hooks:
  #     - id: pip-audit
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        files: src/
        args: [--show-error-code]
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        files: src/
        language: system
        types: [python]
      - id: bandit
        name: bandit
        entry: poetry run bandit
        args: [-c, pyproject.toml, -r]
        files: src/
        language: system
        types: [python]
